name: Hello World Workflow

# Trigger the action on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    name: Say Hello Job
    runs-on: ubuntu-latest  # The environment to run the action

    steps:
      # Step 1: Checkout the code (required in GitHub Actions workflows)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print "Hello, World!" in the console
      - name: Print Hello World
        run: echo "Hello, World!"
